CREATE TABLE "DIS_STUDENTS" (
	"STD_ID" IDENTITY NOT NULL,
	"STD_FNAME" VARCHAR(100),
	"STD_LNAME" VARCHAR(100),
	"STD_RATE" DECIMAL(4, 1),
	"STD_ADD_DATE" TIMESTAMP,
	CONSTRAINT "PK_STUDENTS" PRIMARY KEY ("STD_ID")
);